### ISSUE TITLE
data.py IndexError

### ISSUE THREAD

**Issue by hanclair** [soedinglab/tejaas#7]
Hello,

I am trying to run this program for a non-model organism and hit this error:

2022-09-12 15:57:44,706 | tejaas.utils.args | INFO | Running TEJAAS v1.0.1
2022-09-12 15:57:44,708 | tejaas.utils.args | INFO | Method: rr
2022-09-12 15:57:44,708 | tejaas.utils.args | INFO | Null Model: perm
2022-09-12 15:57:44,709 | tejaas.utils.args | INFO | Sigma_beta: 0.1
2022-09-12 15:57:44,709 | tejaas.main | DEBUG | Using 8 cores
2022-09-12 15:57:44,734 | tejaas.iotools.data | DEBUG | Reading expression levels for trans-eQTL discovery
2022-09-12 15:57:45,115 | tejaas.iotools.data | DEBUG | Reading expression levels for target gene discovery
2022-09-12 15:57:46,065 | tejaas.iotools.data | DEBUG | Found 7155 genes of 218 samples
2022-09-12 15:57:46,065 | tejaas.iotools.data | DEBUG | Reading gencode file for gene information
2022-09-12 15:57:46,220 | tejaas.iotools.data | DEBUG | Selecting common samples of genotype and gene expression
2022-09-12 15:57:46,220 | tejaas.iotools.data | DEBUG | Before expression selection: 7155 genes from 218 samples
Traceback (most recent call last):
  File "/groups/stern/home/hanc/miniconda3/envs/py39/bin/tejaas", line 8, in <module>
    sys.exit(main())
  File "/groups/stern/home/hanc/miniconda3/envs/py39/lib/python3.9/site-packages/tejaas/main.py", line 73, in main
    data.load()
  File "/groups/stern/home/hanc/miniconda3/envs/py39/lib/python3.9/site-packages/tejaas/iotools/data.py", line 248, in load
    expression_selected = rpkm._normalize_expr(expression[:, exprmask][indices, :])
IndexError: arrays used as indices must be of integer (or boolean) type

I am not sure if this is more likely caused by incorrect formatting of my VCF file or expression file? I formatted the expression file exactly as shown in the example, with one column of gene ID names followed by numeric expression values for each sample. 

Any suggestion would be greatly appreciated. Thanks so much for your time.

**Comment by hanclair** [comment]
Sorry I just noticed a similar issue in the closed questions.
